// <auto-generated />
using System;
using Fiap.Web.Alunos.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Api.Alunos.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240624190608_ModelingTables")]
    partial class ModelingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Web.Alunos.Models.CameraSegurancaModel", b =>
                {
                    b.Property<int>("CameraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CameraId"));

                    b.Property<DateTime>("DataFilmagem")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("VideoCamera")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("CameraId");

                    b.ToTable("CameraSeguranca", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Alunos.Models.CentralSegurancaModel", b =>
                {
                    b.Property<int>("CentralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CentralId"));

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("LigarBombeiro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("LigarPolicia")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("SensorId")
                        .IsRequired()
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CentralId");

                    b.HasIndex("UserId");

                    b.ToTable("CentralSeguranca", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Alunos.Models.ChamadasModel", b =>
                {
                    b.Property<int>("LigacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LigacaoId"));

                    b.Property<int>("CentralId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataOcorrido")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("NumeroLigacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("LigacaoId");

                    b.ToTable("Chamadas", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Alunos.Models.SensorIncendioModel", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorId"));

                    b.Property<int>("AlertaSensor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ComodoSensor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("SensorId");

                    b.ToTable("SensorIncendio", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Alunos.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Alunos.Models.CentralSegurancaModel", b =>
                {
                    b.HasOne("Fiap.Web.Alunos.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
