name: Run .NET Tests and Create PR

on:
  push:
    branches:
      - "feature/*"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --no-restore
        id: test
        continue-on-error: false

  create-pr:
    runs-on: ubuntu-latest
    needs: run-tests
    if: success() # Apenas cria o PR se os testes forem bem-sucedidos
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Usar o token padrão do GitHub Actions
          script: |
            const { GITHUB_REF, GITHUB_REPOSITORY } = context;
            const base = "developer";
            const head = GITHUB_REF.replace("refs/heads/", ""); // Remove o prefixo "refs/heads/"
            const title = `Merge feature branch ${head} to developer`;
            const body = `This PR merges the feature branch ${head} into the developer branch.`;

            await github.pulls.create({
              owner: GITHUB_REPOSITORY.split('/')[0],
              repo: GITHUB_REPOSITORY.split('/')[1],
              title: title,
              head: head,
              base: base,
              body: body,
            });
