name: Run .NET Tests and Create PR

on:
  push:
    branches:
      - "feature/*"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --no-restore
        id: test
        continue-on-error: false

  create-pr:
    runs-on: ubuntu-latest
    needs: run-tests
    if: success() # Apenas cria o PR se os testes forem bem-sucedidos
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Usar o token padrão do GitHub Actions
          title: "Merge feature branch to developer"
          body: "This PR merges the feature branch into the developer branch."
          base: developer
          head: ${{ github.ref }} # Refere-se à branch atual
