name: Run .NET Tests and Create PR

on:
  push:
    branches:
      - "feature/*"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --no-restore
        id: test
        continue-on-error: false

      - name: Test GitHub Token Permissions
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls

  create-pr:
    runs-on: ubuntu-latest
    needs: run-tests
    if: success() # Apenas cria o PR se os testes forem bem-sucedidos
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Automated PR for feature/${{ github.head_ref }}`,
              head: `${{ github.head_ref }}`, // Pega o nome do branch
              base: 'developer',
              body: 'This PR was created automatically by the workflow.',
            });
            console.log(`Pull request created: ${response.data.html_url}`);
