name: Build and Create PR

on:
  push:
    branches:
      - "feature/*"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --no-restore
        id: test
        continue-on-error: false

  create-pr:
    runs-on: ubuntu-latest
    needs: run-tests
    if: ${{ success() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log the current branches
        run: git branch -a

      - name: Debug Info
        run: |
          echo "Current Branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Base Branch: developer"
          echo "Feature Branch: feature/testes"
          echo "Git Status: $(git status)"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: developer
          head: feature/testes # Adicionado para indicar de onde criar o PR
          title: "Automated PR from feature branch"
          body: "This PR was automatically created after successful tests."
