name: Create Pull Request main

on:
  workflow_run:
    workflows: ["Build and Deploy"] # Nome do outro workflow
    types:
      - completed

jobs:
  create-pr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Executa apenas se o workflow anterior for bem-sucedido
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const headBranch = context.ref.replace('refs/heads/', ''); // Obtém apenas o nome do branch
            const response = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Automated PR for feature/${headBranch}`,
              head: headBranch, // Pega o nome do branch
              base: 'main',
              body: 'This PR was created automatically by the workflow.',
            });
            console.log(`Pull request created: ${response.data.html_url}`);
